### PR TITLE
Fix Working Hours going through the midnight

### PR DESCRIPTION
**Pull request by m-danya**
This pull request closes issue #94.

### CODE REVIEW

**Comment by m-danya** [comment]
That's not correct, I'll fix it

**Review by tom-james-watson — COMMENTED** [review]
I think this is better addressed by a proper implementation of something like https://github.com/tom-james-watson/breaktimer-app/pull/207.

Thanks for the contribution, though.

**Comment by m-danya** [comment]
Ok. By the way, you've mentioned my PR in your message. I suppose you had another one in mind, but that's funny :)

**Comment by tom-james-watson** [comment]
Hah oops! I meant https://github.com/tom-james-watson/breaktimer-app/pull/217

**Pull request closed without merging**
