### PR TITLE
Ability to start break right away within notification popup

### PR DESCRIPTION
**Pull request by whyyor**
## What?
Add a toggle button to start breaks right away in notification pop up

## Why?
During watching lectures or coding when notification pops up I only have option to wait for the break to start so for that I wanted a start now button. 

Even when I enable snooze I keep pressing snooze just to avoid waiting for notification pop up to complete so I though start button would be great

## How?
This includes a start button in notification pop up under snooze and skip which can be toggled in settings. Used pre-existing code and made some new variables.

### CODE REVIEW

**Comment by tom-james-watson** [comment]
Hello! Thanks for your PR.

At the moment, if you disable skip break and snooze break, you don't get the break countdown. With that being the case, I'm not sure what the value of this actually is?

**Comment by whyyor** [comment]
Hi thanks for response.

It's just that I always use snooze and start feature would be great! But if I add a change code so that when skip and snooze are disabled but start it enabled then notification pop up then would it be a valuable feature?

By default the start toggle will be disabled, but I think start button in notification will be really helpful.

**Comment by tom-james-watson** [comment]
Ok, I'll try and find some time to take a look at it properly soon!

**Comment by tom-james-watson** [comment]
I'm afraid this doesn't really fit and I don't think it's something I'd want to merge, unfortunately. Sorry about the delay, too.

**Pull request closed without merging**
