### PR TITLE
stop macos dock icon from appearing

### PR DESCRIPTION
**Pull request by tom-james-watson**

### CODE REVIEW

**Comment by bnoctis** [comment]
The icon does not appear anymore now, however, focus is somehow still "stolen". 🤦

Menu bar app continues to be the foreground app before popup pops up, but after it hides itself, focus is not returned.

**Comment by tom-james-watson** [comment]
Ah, you're right. I can't check your old PR anymore to see if it worked differently because it looks like you've deleted the fork.

**Comment by bnoctis** [comment]
Simple enough - `app.hide() && app.dock.hide()` in `endPopupBreak` and `postponeBreak`. Still, not that deep down the hole, so rather a workaround than solution.

**Comment by tom-james-watson** [comment]
I've just published 1.0.3 which hopefully should get this right now!

**Comment by tom-james-watson** [comment]
See https://github.com/tom-james-watson/breaktimer-app/commit/126d48398db42dae776ea4b7987d3d3d11881626

**Pull request merged**
